# Generated by Django 6.0.7 on 2026-07-13 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='💰', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Grant Categories',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('type', models.CharField(choices=[('scholarship', 'Scholarship'), ('grant', 'Grant'), ('fellowship', 'Fellowship'), ('internship', 'Internship'), ('job', 'Job')], default='grant', max_length=20)),
                ('funder', models.CharField(max_length=200)),
                ('funder_logo', models.ImageField(blank=True, null=True, upload_to='funders/')),
                ('description', models.TextField()),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('eligibility', models.CharField(choices=[('ngo', 'NGO / Non-Profit'), ('individual', 'Individual'), ('student', 'Student'), ('researcher', 'Researcher'), ('organization', 'Organization'), ('any', 'Anyone')], default='any', max_length=20)),
                ('countries', models.TextField(blank=True, help_text='Comma separated country codes')),
                ('deadline', models.DateField()),
                ('apply_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], default='open', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grants.grantcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
